server:
  port: 8080





eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
      
        - id: authentication-service
          uri: http://localhost:8091
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}

        - id: buyer-user-service
          uri: http://localhost:8089
          predicates:
            - Path=/buyer/**
          filters:
            - RewritePath=/buyer(?<segment>/?.*), $\{segment}
        - id: seller-user-service
          uri: http://localhost:8090
          predicates:
            - Path=/seller/**
          filters:
            - RewritePath=/seller(?<segment>/?.*), $\{segment}

        - id: product-service
          uri: http://localhost:8092
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8096
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8094
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        - id: order-service
          uri: http://localhost:8095
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order(?<segment>/?.*), $\{segment}

        - id: cart-service
          uri: http://localhost:8093
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart(?<segment>/?.*), $\{segment}
